### ISSUE TITLE
Temperature/humidity sensors show zero value when using local

### ISSUE THREAD

**Issue by tmds** [openmotics/home-assistant#16]
I have changed from using the cloud connection to using a local connection.
When using the cloud connection, values from temperature and humidity sensors were reported in hass.
With the local connection, all these sensors report a value of zero.

cc @woutercoppens

**Comment by woutercoppens** [comment]
If you connect directly to the local gateway, do the sensors report the correct values? 
It's not clear from your description if it's a bug in pyhaopenmotics or in the gateway.

**Comment by tmds** [comment]
I'm looking at the code in https://github.com/openmotics/pyhaopenmotics.

I see `sensors.py` is using `get_sensor_configurations` and `get_sensor_status`.

The json for these endpoints looks something like:
```json
{
    "config": [
        {
            "name": "Leefruimte",
            "in_use": true,
            "external_id": "1",
            "virtual": false,
            "source": {
                "type": "master",
                "name": null
            },
            "offset": 0,
            "physical_quantity": "temperature",
            "id": 1,
            "unit": "celcius",
            "room": 0
        },
        {
            "name": "Leefruimte",
            "in_use": true,
            "external_id": "1",
            "virtual": false,
            "source": {
                "type": "master",
                "name": null
            },
            "offset": 0,
            "physical_quantity": "humidity",
            "id": 4,
            "unit": "percent",
            "room": 255
        }
    ],
    "success": true
}
```
and
```json
{
    "status": [
        {
            "id": 1,
            "value": 22.0
        },
        {
            "id": 4,
            "value": 57.0
        }
    ],
    "success": true
}
```

This last one doesn't seem to match with what's expected by
[Status.from_dict](https://github.com/openmotics/pyhaopenmotics/blob/0eec425be3543d0220cc49a6f95132dc941cd7d3/src/pyhaopenmotics/openmoticsgw/models/sensor.py#L19-L33).

**Comment by tmds** [comment]
I patched
```
            # on = True if status = 1
            humidity=data.get("humidity", 0),
            temperature=data.get("temperature", 0),
            brightness=data.get("brightness", 0),
```
to
```
            humidity=data.get("value", 0),
            temperature=data.get("value", 0),
            brightness=data.get("value", 0),
```
and now sensor values are reported.

**Comment by woutercoppens** [comment]
Hi Tom,

I'm currently in the middle of a construction. I'll have a look at in the next weeks.
Are you running the last version on the gateway?

**Comment by tmds** [comment]
Yes, I'm running the latest version (`2.25.4`).

There's no rush, I can see the values with the patch.
