### ISSUE TITLE
Contributing to the project

### ISSUE THREAD

**Issue by AdrianFlack** [openmotics/home-assistant#2]
Hi,

I've got the project up and running with home-assistant and have made a few additions. I've now got OpenMotics lights that are connected to dimmer modules showing in Home-Assistant with a brightness slider with values scaled correctly between OpenMotics and Home-Assistant. What's the best way for me to contribute to the project, a pull request from a branch or from a fork?

Cheers
Adrian

**Comment by AdrianFlack** [comment]
Hi Wouter, 

I've sent you a pull request from my fork of home-assistant. Let me know if there's anything you want changed/addressed

Cheers
Adrian

**Comment by AdrianFlack** [comment]
Hi Wouter, I’ll close this ticket now. 

Thanks
Adrian

**Comment by woutercoppens** [comment]
Hi Adrian,

A friend of mine has installed your code and has some issues. Can we have
your email address to discuss this directly?
My installation is very simple: I only have light bulbs (not even dimmable)
and it's not that easy to simulate things.

Regards,

Wouter

Op do 10 mei 2018 om 21:08 schreef AdrianFlack <notifications@github.com>:

**Comment by khenderick** [comment]
If it would turn out to be a configuration issue, it might be interesting to document these in the wiki.

**Comment by AdrianFlack** [comment]
Apologise Wouter, I didn’t have notifications turned on, so didn’t see your comment. If your friend still needs help, my email address is Adrian.flack@gmail.com
