### ISSUE TITLE
Shutter output

### ISSUE THREAD

**Issue by wash34000** [openmotics/home-assistant#4]
Hello,

I'm so happy to find this component for OpenMotics and Hass !!
I have a question about output module in shutter mode, is it functionnal ? 
I'm trying to make it appear in Hass but nothing appear. Do you have any clue for me ?

Thanks

**Comment by woutercoppens** [comment]
Hi,

I have no shutters in my setup, so I cannot test it. If you're willing tot
give me the output of your config, I'll give it a try.

Op ma 29 okt. 2018 om 19:56 schreef wash34000 <notifications@github.com>

**Comment by wash34000** [comment]
Hello,

I have wrote a small extention for shutter mode its not completely
functional. I'll send you file for your github if you want when it will be
ready.

Do you know how reload custom component without reboot?

Kind regards


Le jeu. 1 nov. 2018 à 11:03, Wouter Coppens <notifications@github.com> a
écrit :

**Comment by woutercoppens** [comment]
Hey,

We have builtin support for scenes and dimmers in the dev tree. Maybe this can help you?

W.

**Comment by AdrianFlack** [comment]
Is there any update for shutters? If OpenMotics has shutters available I’m keen to create an integration with home-assistant ‘covers’

**Comment by wash34000** [comment]
Hello,
Sorry for long time without news. 
For now i've implemented Home-assistant 'covers' but the current python SDK doesn't give possibility to get Shutter/Roller informations. Is it right ?

Maybe we could fork this SDK integration and add shutter function like for web API request : https://XX.XX.XX.XX/get_shutter_configurations?token=ABCD

Or Maybe a newest SDK version is ready ?

**Comment by khenderick** [comment]
Hi all,

First of all, thanks again for the interest.

This repo uses @woutercoppens's SDK (fork), but we also have our own at openmotics/sdk. However, to be honest here, at this moment, we don't have enough time to maintain this SDK as it's kept in sync manually. However, it's high on our wishlist to have a decent up-to-date (preferably auto generated/validated) SDK, so if PRs would be opened against this repo, we'll sure give priority to reviewing and accepting them.

If interested in enhancing the SDK, the Gateway's code exposing this API is fairly readable, from https://github.com/openmotics/gateway/blob/develop/src/gateway/webservice.py#L526 and below. All available calls are decorated using @openmotics_api(...) and a lot of them have some metadata added.

**Comment by woutercoppens** [comment]
Hi all,

I had to fork the SDK because it was written for Python 2 and HA uses
Python 3. However the changes were very minimal (1 change if I remember
correctly)

W.

Op ma 23 sep. 2019 om 09:49 schreef Kenneth Henderick <
notifications@github.com>:

**Comment by wash34000** [comment]
Yes I found just one small difference on line 69:
-- print "Fetching url: %s" % url
++ print("Fetching url: %s" % url)

**Comment by wash34000** [comment]
I brought some additional functions for shutters to the SDK. Who should I give them to respect your available time and your process?



    def get_shutter_status(self):
        """ Get the status of the shutters.

        :returns: a dict with this elements :
        'status': global status dict of all shutter order by id
        'detail': dict of id shutters with the following keys: state, desired_position, actual_position.
        """
        return self.exec_action('get_shutter_status')


    def do_shutter_up(self, id):
        """ Open a shutter.

        :param id: The id of the shutter to open
        :type id: Integer [0, 240]
        """
        post_data = {'id' : id}
        return self.exec_action('do_shutter_up', post_data=post_data)        


    def do_shutter_down(self, id):
        """ Close a shutter.

        :param id: The id of the shutter to close
        :type id: Integer [0, 240]
        """
        post_data = {'id' : id}
        return self.exec_action('do_shutter_down', post_data=post_data)    


    def do_shutter_stop(self, id):
        """ Stop a shutter.

        :param id: The id of the shutter to stop
        :type id: Integer [0, 240]
        """
        post_data = {'id' : id}
        return self.exec_action('do_shutter_stop', post_data=post_data)      

     
    def get_shutter_configuration(self, id):
        """
        Get a specific shutter_configuration defined by its id.

        :param id: The id of the shutter_configuration
        :returns: 'config': shutter_configuration dict: contains 'id' (Id), 'group_1' (Byte), 'group_2' (Byte), 'name' (String[16]), 'room' (Byte), 'timer_down' (Byte), 'timer_up' (Byte), 'up_down_config' (Byte)
        :rtype: dict
        """
        return self.exec_action("get_shutter_configuration", post_data = { "id" : id })
    

    def get_shutter_configurations(self):
        """
        Get all shutter_configurations.

        :returns: 'config': list of shutter_configuration dict: contains 'id' (Id), 'group_1' (Byte), 'group_2' (Byte), 'name' (String[16]), 'room' (Byte), 'timer_down' (Byte), 'timer_up' (Byte), 'up_down_config' (Byte)
        :rtype: dict
        """
        return self.exec_action("get_shutter_configurations")

**Comment by khenderick** [comment]
Did you implement this on a fork of this repo? If so, the best is to open a pull request. You can find some information on how to do that here: https://help.github.com/en/articles/creating-a-pull-request-from-a-fork but let us know if things are not clear.

**Comment by woutercoppens** [comment]
old issue
