### ISSUE TITLE
Fault message after install Openmotics - Home Assistant integration

### ISSUE THREAD

**Issue by rmvandek** [openmotics/home-assistant#47]
Hi,

I try to install the Openmotics integration for Home Assistant. Looks al finally is installed (with Hacs). After I fill in the credentials (cloud) it looks that the process is verified and ok, but when the integration try to start-up it give a fault message. Messages is that he gives 3 validation errors. I have uninstall and downloaded all many times and try new credential in openmotis and also few times configuration reset all result in same issue.
I use Home assistant core 2023.12.4 and supervisor 2023.12.0. my openmotics gateway is system version 3.3.2 and firmware 3.143.126.
The log shows : 

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openmotics/coordinator.py", line 58, in _async_update_data
    my_sensors = await self._omclient.sensors.get_all()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyhaopenmotics/cloud/sensors.py", line 56, in get_all
    return parse_obj_as(list[Sensor], body["data"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/tools.py", line 38, in pydantic.tools.parse_obj_as
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 3 validation errors for ParsingModel[list[pyhaopenmotics.cloud.models.sensor.Sensor]]
__root__ -> 8 -> status
  none is not an allowed value (type=type_error.none.not_allowed)
__root__ -> 9 -> status
  none is not an allowed value (type=type_error.none.not_allowed)
__root__ -> 12 -> status
  none is not an allowed value (type=type_error.none.not_allowed)

What can I do to resolve this? Thanks, Reinoud

**Comment by woutercoppens** [comment]
My gateway is version 3.5.1 but that should not make any differences. 

I assume that you have more then the 3 sensors that gave validation errors? There is probably something wrong with the configuration of these 3 sensors. 
There is no way to see if a sensor is configured or not. The integration checks if a name is defined or not. It a name is configured, it assumes that it is in use. 
If those sensors are not in use, can you delete the name? Or replace it with None?

**Comment by rmvandek** [comment]
Hi Wouter,

First of all thanks for all the work you put in and the reaction. 
I have upgrade it to 3.5.1. but see, till now, no change. I have two sensor modules and 9 temp/hum. sensors connected. I try to open the sensor window in the openmotics and see that they have change the layout. I see all the connected sensors but not the other not in used sensor inputs. I cant find a way to see the unused sensor inputs. Its changed do you know how to show the unused inputs. Probably I have to make a ticket in the openmotics. If I am able I will try your suggestions and come back on this.  

![sensor_window](https://github.com/openmotics/home-assistant/assets/86572059/c1ea9874-7980-458d-aa98-cbad258eaff1)

**Comment by rmvandek** [comment]
Hi Wouter,
I have send a request to OpenMotics and get there final reaction last week.
I had a problem with room names that were double and therefore not well
attached with some sensors. It seems that when you delete a floor with some
rooms that are still attached, the attached rooms are not deleted and still
available. So I had double rooms and not well attached to the sensors.
I have changed the attached rooms and downloaded the openmotics home
assistant integration again and it works well. Thanks for the great
integration and support.
Gr Reinoud





Op di 23 jan 2024 om 17:12 schreef Wouter Coppens ***@***.***
