### ISSUE TITLE
dimmer value is not being applied when turning on light

### ISSUE THREAD

**Issue by benjaminfrombe** [openmotics/home-assistant#49]
When you set a dimmer to, say 50%, then turn off the light and later switch it back on, it dims to 100%, seems to be a small bug ...

**Comment by woutercoppens** [comment]
Is it the same behavior when using the Ios/Android app? Of when using the
OM portal?

Op ma 1 jan. 2024 om 20:17 schreef benjaminfrombe ***@***.***>

**Comment by benjaminfrombe** [comment]
Yea, behavior is the same in the iOS App (Dimmer value is not applied), in the Openmotics app it works correctly …

**Comment by woutercoppens** [comment]
Strange, the code supports dimming and you're the first who makes a remark about it.
Are you using the local gateway version or the cloud? 

Can you add this to your configuration.yaml?
'''
logger:
  default: info
  logs:
    custom_components.openmotics: debug
'''
and upload relevant messages about your lights?

**Comment by benjaminfrombe** [comment]
I'm using the local connection. Tried cloud but I get a different error (below)

if I enable debug logging I don't see a lot, only:
2024-01-07 19:10:26.449 DEBUG (MainThread) [custom_components.openmotics.light] Turning off light: 18
2024-01-07 19:10:30.932 DEBUG (MainThread) [custom_components.openmotics.light] Turning on light: 18



When trying the cloud connection, I get this:

This error originated from a custom integration.

Logger: custom_components.openmotics.coordinator
Source: helpers/update_coordinator.py:300
Integration: OpenMotics (documentation, issues)
First occurred: 7:45:22 PM (7 occurrences)
Last logged: 7:47:31 PM

Unexpected error fetching openmotics-clouddev-15 data: 1 validation error for ParsingModel[list[pyhaopenmotics.cloud.models.sensor.Sensor]] __root__ -> 5 -> status none is not an allowed value (type=type_error.none.not_allowed)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openmotics/coordinator.py", line 58, in _async_update_data
    my_sensors = await self._omclient.sensors.get_all()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyhaopenmotics/cloud/sensors.py", line 56, in get_all
    return parse_obj_as(list[Sensor], body["data"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/tools.py", line 38, in parse_obj_as
    return model_type(__root__=obj).__root__
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[list[pyhaopenmotics.cloud.models.sensor.Sensor]]
__root__ -> 5 -> status
  none is not an allowed value (type=type_error.none.not_allowed)

**Comment by woutercoppens** [comment]
Hi Benjamin,

Can you send me a mail at wouter dot coppens at gmail dot com? 
You lights are not detected as dimmers. I would like to take a look in your system.
