### ISSUE TITLE
Lastest `dev` branch config error with home-assistant

### ISSUE THREAD

**Issue by AdrianFlack** [openmotics/home-assistant#7]
Hi,

I just wanted to try out the latest `dev` branch to see how the covers/shutters' were working, but I get an `Invalid Config` error when starting up home-assistant. Debug logs show the following error:
```Unable to install package openmotics-cloud-sdk==0.0.11: ERROR: Could not find a version that satisfies the requirement openmotics-cloud-sdk==0.0.11 (from versions: none) ERROR: No matching distribution found for openmotics-cloud-sdk==0.0.11```
Is the cloud sdk something that is being worked on and not available yet?

Thanks
Adrian

**Comment by woutercoppens** [comment]
Hi Adrian,

The cloud sdk is currently hosted on a private repository, so it's normal that you receive the error.

Regards,

Wouter
