### ISSUE TITLE
Openmotics custom configuration fails to load with latest home-assistant version

### ISSUE THREAD

**Issue by AdrianFlack** [openmotics/home-assistant#8]
I've just updated my home-assistant version from `2021.1.5 ` to `2021.7.1` and the openmotics custom config fails to load. 

Log error reads:

Unknown error connecting with OpenMotics controller: I/O must be done in the executor, use `await hass.async_add_executor_job()` at custom_components/openmotics/openmoticssdk.py line: 75 `r = requests.post(url, params=get_params, data=post_data, verify=self.verify_https)`

I've rolled back to my previous home-assistant version, but if no one else is looking at the issue, I might have a go at fixing it.

Cheers
Adrian

**Comment by AdrianFlack** [comment]
Actually, rolling back to. 2021.5.1 has not worked

**Comment by kneirinck** [comment]
By coincidence I updated from 0.99.2 to 2021.7.1 yesterday evening.
Took a bit to get it going again but got it working.
I can have a look into cleanup up my workarounds and creating a PR if you want?

**Comment by kneirinck** [comment]
https://github.com/openmotics/home-assistant/pull/9

**Comment by woutercoppens** [comment]
Hi Adrian and Klaas,

Openmotics is currently working on a new Python sdk but it's currently in private beta. 
Can we take this offline and discuss it privately? Plz send email to wouter dot coppens at gmail dot com.

**Comment by DCL777** [comment]
Hi @woutercoppens ,

First at all, thanks for the great work you did on you HA Openmotics component.  I used it already serveral years.

Today, I just updated HA from 2021.3 to 2021.11.1 and i receive the following error while checking the configuration:
_Configuration invalid: "Integration error: openmotics - Integration 'openmotics' not found."_

![image](https://user-images.githubusercontent.com/55956951/140616368-411541e5-a6d6-4b99-a92d-1c45cbe6a7aa.png)

I did the test with the "Master" and the "Dev"-repo.
is that the same issue as described above?
On 11/07, you were talking about a new sdk together with Openmotics.  Is it ready to use?
is there some kind of a fix, to use it with the latest HA?

Thanks a lot,

Kind regards,

Dries Claerbout

**Comment by woutercoppens** [comment]
Hi Dries,


I wrote my own sdk to access the openmotics api's. The official cloud-sdk
has very low priority from OpenMotics. I have PR's open for more than a
month.

If you want to play with it:
https://github.com/woutercoppens/python-openmotics (required for the custom
home assistant integration)
https://github.com/woutercoppens/home-assistant

I still need to do some code cleanup, but the first tests are successful.

Regards,

Wouter

Op za 6 nov. 2021 om 16:15 schreef DCL777 ***@***.***>

**Comment by tpires** [comment]
I've fork @kneirinck branch from #9 and updated it to work with HomeAssistant `2021.21.5`. 
I've also added support to temperature and humidity sensors.

There are some issues around the lights not updating correctly, which I'm looking to fix.

**Comment by pietew** [comment]
So if I understand correctly, the plugin on OpenMotics' github page is simply not compatible with any recent version of Home Assistant. I'm now running HA 2021.12.8.

@khenderick can you please update the plugin page? Based on this thread, it seems like one has found the solution.

Thanks in advance!

**Comment by khenderick** [comment]
@tpires can you open a PR?

**Comment by tpires** [comment]
@khenderick it's still a work in progress. I'll raise one when it's ready.

**Comment by woutercoppens** [comment]
> So if I understand correctly, the plugin on OpenMotics' github page is simply not compatible with any recent version of Home Assistant. I'm now running HA 2021.12.8.
> 
> @khenderick can you please update the plugin page? Based on this thread, it seems like one has found the solution.
> 
> Thanks in advance!

@pietew;
Hi all,

I need some guinea pigs to test some things:
https://github.com/woutercoppens/home-assistant-v3

Complete rewrite based on aiohttp, hacs and client_id/client_secret. 

Before using this version, remove the previous integration/configuration.

There are also the first steps to use the local gateway, but i cannot test it because my gateway is too old. 

Please let me know what you think,

**Comment by verwilst** [comment]
@woutercoppens Just installed v3 through HACS, very basic test, added a light, and i can turn it off and on! Awesome work! Getting the error "Failed to call service light/turn_on. unsupported operand type(s) for -: 'int' and 'NoneType'" on each press though.

**Comment by woutercoppens** [comment]
latest codebase uploaded
